### PR TITLE
MANE added as a string (MANE_status) instead of flag

### PR DESCRIPTION
**Pull request by cnascim1**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_add_MANE_annotation/3)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_add_MANE_annotation/3)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @cnascim1)

___
*[`resources/home/dnanexus/add_MANE_annotation.py` line 53 at r2](https://reviewable.io/reviews/eastgenomics/eggd_add_MANE_annotation/3#-NqbzYwT2tbyhvPOTFPx:-NqbzYwT2tbyhvPOTFPy:bo4hny7) ([raw file](https://github.com/eastgenomics/eggd_add_MANE_annotation/blob/1c10a3e66d1ba499142f733738647d685703ef60/resources/home/dnanexus/add_MANE_annotation.py#L53)):*
> ```Python
>     transcript_file_table = pd.read_table(
>     args.transcript_file
>     )
> ```

does this need to be on new lines?



_Code quote:_
```Python
    args.transcript_file
    )
```
___
*[`resources/home/dnanexus/vcf.py` line 187 at r2](https://reviewable.io/reviews/eastgenomics/eggd_add_MANE_annotation/3#-Nqc--Tp-2OrDs3CY9f7:-Nqc--Tp-2OrDs3CY9f8:b-a8yhpv) ([raw file](https://github.com/eastgenomics/eggd_add_MANE_annotation/blob/1c10a3e66d1ba499142f733738647d685703ef60/resources/home/dnanexus/vcf.py#L187)):*
> ```Python
>         for variant in variant_list:
>             if all([transcript_present, transcript_mane]):
>                 variant.info['MANE'] = transcript_mane
> ```

from your example, is this where `"MANE Select"` is coming from? If so, it's breaking the VCF spec by having whitspace in an INFO field value:
```
INFO - additional information: (String, no whitespace, semicolons, or equals-signs permitted; commas are
permitted only as delimiters for lists of values) 
```
https://samtools.github.io/hts-specs/VCFv4.2.pdf

can we have a `.replace(' ', '_')` or something here to handle it



_Code quote:_
```Python
transcript_mane
```

**Review by cnascim1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_add_MANE_annotation/3)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/add_MANE_annotation.py` line 53 at r2](https://reviewable.io/reviews/eastgenomics/eggd_add_MANE_annotation/3#-NqbzYwT2tbyhvPOTFPx:-NqcFmHB7VFVRFyxVs_L:bdn9zu8) ([raw file](https://github.com/eastgenomics/eggd_add_MANE_annotation/blob/1c10a3e66d1ba499142f733738647d685703ef60/resources/home/dnanexus/add_MANE_annotation.py#L53)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

does this need to be on new lines?
</blockquote></details>

same line now :)
___
*[`resources/home/dnanexus/vcf.py` line 187 at r2](https://reviewable.io/reviews/eastgenomics/eggd_add_MANE_annotation/3#-Nqc--Tp-2OrDs3CY9f7:-NqcF_HACDyfTsPrB0vp:b-31o6nx) ([raw file](https://github.com/eastgenomics/eggd_add_MANE_annotation/blob/1c10a3e66d1ba499142f733738647d685703ef60/resources/home/dnanexus/vcf.py#L187)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

from your example, is this where `"MANE Select"` is coming from? If so, it's breaking the VCF spec by having whitspace in an INFO field value:
```
INFO - additional information: (String, no whitespace, semicolons, or equals-signs permitted; commas are
permitted only as delimiters for lists of values) 
```
https://samtools.github.io/hts-specs/VCFv4.2.pdf

can we have a `.replace(' ', '_')` or something here to handle it
</blockquote></details>

yes, sorry.  Fixed, added `.replace(' ', '_')`

**Review by jethror1 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_add_MANE_annotation/3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cnascim1)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_add_MANE_annotation/3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cnascim1)

**Pull request merged**
