### PR TITLE
Initial app file structure

### PR DESCRIPTION
**Pull request by cnascim1**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_add_MANE_annotation/1)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1)* status: 8 of 13 files reviewed, 15 unresolved discussions (waiting on @cnascim1)

___
*[`dxapp.json` line 9 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_Yk_N0uowPTDQ1Hwt:-Np_Yk_N0uowPTDQ1Hwu:b-ahy21) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/dxapp.json#L9)):*
> ```JSON
>     "inputSpec": [
>         {
>         "name": "input_file",
> ```

could this be changed to `vcf` or `vcf_file` or similar to be more descriptive please



_Code quote:_
```JSON
input_file
```
___
*[`dxapp.json` line 26 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_YXW46zCAvRSRciM2:-Np_YXW46zCAvRSRciM3:b-2cex90) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/dxapp.json#L26)):*
> ```JSON
>             "id": "file-Gfxpkj04Jkkvx7VG22kpQK5z"
>             }
>         ]
> ```

since this isn't in 001_Reference project can the suggestion just be removed? This will be added in a workflow and probabbly not run interactively, so not really needed



_Code quote:_
```JSON
        "suggestions": [
            {
            "project": "project-GfxkbY84JkkxvVbXYv5z3948",
            "id": "file-Gfxpkj04Jkkvx7VG22kpQK5z"
            }
        ]
```
___
*[`dxapp.json` line 34 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_YsXl9od9Ol1XhUUh:-Np_YsXl9od9Ol1XhUUi:b1en9sx) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/dxapp.json#L34)):*
> ```JSON
>         "label": "sample vcfs, with extra MANE flag added",
>         "class": "file"
>         }
> ```

since this just outputs a single vcf, can this just be `vcf` or `output_vcf` etc



_Code quote:_
```JSON
        {
        "name": "result_files",
        "label": "sample vcfs, with extra MANE flag added",
        "class": "file"
        }
```
___
*[`dxapp.json` line 45 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_Z3TW08dkY1gmANTo:-Np_Z3TW08dkY1gmANTp:b-momvtp) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/dxapp.json#L45)):*
> ```JSON
>         "*": {
>             "hours": 3
>         }
> ```

I assume this is very quick, could this just be 1 hour?



_Code quote:_
```JSON
        "timeoutPolicy": {
        "*": {
            "hours": 3
        }
```
___
*[`dxapp.json` line 59 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_ZBWf2LDR_r1oKkT4:-Np_ZBWf2LDR_r1oKkT5:b8vbiug) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/dxapp.json#L59)):*
> ```JSON
>             "folder": "/app_assets/python_packages/python_packages_v1.1.0",
>             "version": "1.1.0"
>         }
> ```

I don't think this is needed is it? do you have the Python whl files needed in `/resources/home/dnanexus/packages`?



_Code quote:_
```JSON
        {
            "name": "python_packages",
            "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
            "folder": "/app_assets/python_packages/python_packages_v1.1.0",
            "version": "1.1.0"
        }
```
___
*[`dxapp.json` line 72 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_ZKTJ2uuBzlnaGnGa:-Np_ZKTJ2uuBzlnaGnGb:bwusumf) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/dxapp.json#L72)):*
> ```JSON
>         "network": [
>         "*"
>         ]
> ```

don't think is needed too, probably better to not have it to make sure we're not unintentionally relying on something remote



_Code quote:_
```JSON
        "network": [
        "*"
        ]
```
___
*[`README.md` line 9 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_ZVAb4Amrk5QWAYg9:-Np_ZVAb4Amrk5QWAYgA:b-nfyph5) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/README.md#L9)):*
> ```Markdown
> dx run app-GZ9FZ78457v7qjBXPXqGByyP \
>     -iinput_vcf=[annotated vcf] \
>     -itranscript_file=[MANE file] \
> ```

make sure these inputs match whats in the dxapp.json :slightly_smiling_face: 



_Code quote:_
```Markdown
    -iinput_vcf=[annotated vcf] \
    -itranscript_file=[MANE file] \
```
___
*[`resources/home/dnanexus/vcf.py` line 75 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_ZzIyA1_uAt64pChz:-Np_ZzIyA1_uAt64pCi-:b6h9ubu) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/resources/home/dnanexus/vcf.py#L75)):*
> ```Python
>     cmd = (
>         f"bcftools +split-vep --columns - -a CSQ -Ou -p 'CSQ_'"
>         f" -d {input_vcf} | bcftools annotate -x INFO/CSQ -o {output_vcf}"
> ```

fyi if you're not familiar with this in bcftools its splitting the vep annotation which is all stored in a single INFO field string as `CSQ=...` into individual fields (i.e. the AFs and ClinVar annotation), this adds ` prefix of `CSQ_` with the `-p` option to each of the fields to stop any duplicates of other INFO fields and to know it is from the VEP annotation string. It then removes the original VEP CSQ INFO string with `bcftools annoatate -x` since it's no longer needed



_Code quote:_
```Python
        f"bcftools +split-vep --columns - -a CSQ -Ou -p 'CSQ_'"
        f" -d {input_vcf} | bcftools annotate -x INFO/CSQ -o {output_vcf}"
```
___
*[`resources/home/dnanexus/vcf.py` line 151 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_a1FQ7iKmc_tnHjh9:-Np_a1FR394BVfzSTQat:b-old9y9) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/resources/home/dnanexus/vcf.py#L151)):*
> ```Python
>         pysam object containing all the VCF's info
>     panel_dict : dict
>         default dict with gene symbol as key and gene info as val
> ```

input param doesn't match actual input



_Code quote:_
```Python
    panel_dict : dict
        default dict with gene symbol as key and gene info as val
```
___
*[`resources/home/dnanexus/vcf.py` line 163 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_adByDrOSd0mdnNWi:-Np_adByDrOSd0mdnNWj:bkr71nl) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/resources/home/dnanexus/vcf.py#L163)):*
> ```Python
>     gene_variant_dict = defaultdict(list)
>     for variant_record in vcf_contents:
>         gene = variant_record.info['CSQ_Feature'][0]
> ```

CSQ_Feature is transcript technically, minor thing but you will be creating a dict here of `{'transcript': [variant_1, variant_2]...}` and not gene, so could have multiple entries in the dict for one gene where it has more than one transcript annotation. Functionally it probably makes no difference, just for making it easier to understand what its doing :slightly_smiling_face: 



_Code quote:_
```Python
gene
```
___
*[`resources/home/dnanexus/vcf.py` line 316 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_bwje-os0yF8fJlG6:-Np_bwjf9YYvJz9s3qsZ:baorv29) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/resources/home/dnanexus/vcf.py#L316)):*
> ```Python
>     )
> 
>     assert pre_sort == post_sort, (
> ```

it can be nice to add into the header a `Raises` section for any Exceptions you purposely might raise (or be raised from asserts), can make it easier to debug too having the context explained for future us, example here: https://github.com/eastgenomics/eggd_dias_batch/blob/18afe48d873e374e284e9e65b818cdc87945c6fe/resources/home/dnanexus/dias_batch/utils/utils.py#L426
___
*[`src/code.sh` line 5 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_cKaa2F3zKl_RldUb:-Np_cKab1LIBNoXe7Wwu:b-84hzdp) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/src/code.sh#L5)):*
> ```Shell
> #
> # Any code outside of main() (or any entry point you may add) is
> # ALWAYS executed, followed by running the entry point itself.
> ```

these are just lines from the dx-app-wizard and can be deleted



_Code quote:_
```Shell
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
```
___
*[`src/code.sh` line 21 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_cTRiBNzLNBVFSPsY:-Np_cTRiBNzLNBVFSPsZ:ben5zw5) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/src/code.sh#L21)):*
> ```Shell
> 
>     # run tool
>     python3 /add_MANE_annotation.py \
> ```

this leading slash can be removed if your script is in `/resources/home/dnanexus/` as when the app starts it will be in the current working directory



_Code quote:_
```Shell
/
```
___
*[`src/code.sh` line 23 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_cQSo9UnuHbMSnjZK:-Np_cQSo9UnuHbMSnjZL:b-jwx8ta) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/src/code.sh#L23)):*
> ```Shell
>     python3 /add_MANE_annotation.py \
>         -i $input_file_path \
>         -f $transcript_file_path 
> ```

make sure these match the dxapp.json and the readme example



_Code quote:_
```Shell
        -i $input_file_path \
        -f $transcript_file_path
```
___
*[`src/code.sh` line 26 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_cgAM-fBdPVdBw3ND:-Np_cgANDbRbc-4nR5vg:bmbq8z5) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/src/code.sh#L26)):*
> ```Shell
>     # prepare outputs
>     echo "All scripts finished successfully, uploading output files to dx"
>     if [ "$debug_fail_end" == 'true' ]; then exit 1; fi
> ```

this line can be deleted as this isn't an input here



_Code quote:_
```Shell
if [ "$debug_fail_end" == 'true' ]; then exit 1; fi
```
___
*[`src/code.sh` line 28 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_cm7b6-uQhmbh-g5G:-Np_cm7b6-uQhmbh-g5H:b-j9690c) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/src/code.sh#L28)):*
> ```Shell
>     if [ "$debug_fail_end" == 'true' ]; then exit 1; fi
>     mkdir -p ~/out/result_files/
>     mv *.vcf.gz ~/out/result_files/
> ```

make sure this `out/dir_name` matches the output field in your dxapp.json output spec



_Code quote:_
```Shell
    mkdir -p ~/out/result_files/
    mv *.vcf.gz ~/out/result_files/
```

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1)* status: 8 of 13 files reviewed, 16 unresolved discussions (waiting on @cnascim1)

___
*[`README.md` line 1 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-NpdJ0VPErQHj0vbiI0W:-NpdJ0VSDEZDWf1C1DYQ:b-9n9b96) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/README.md#L1)):*
> ```Markdown
> eggd_add_MANE_annotation
> ```

could you also make this fit the template example to match our other app readme structure, should be this:

```
<!-- dx-header -->
# AmazingApp (DNAnexus Platform App)
This could be used as a starting point when developing new apps for DNAnexus

<!-- Insert a description of your app here -->
## What does this app do?
Provide a brief description of this tool.

## What are the typical use cases for this app?
Describe use cases of the app.

## What are the inputs?
- list the required input files, specifying any formatting requirements

## What are the outputs?
- list the expected output files, specifying the format

## How to run this app from command line?
\```
add an example command of running this app from the CLI \
especially the (optional) inputs \
and recommended istance_type
\```

### This app was made by EMEE GLH
```


this is a useful page too for markdown syntax supported by GitHub: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Review by cnascim1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1)* status: 8 of 13 files reviewed, 16 unresolved discussions (waiting on @jethror1)

___
*[`dxapp.json` line 9 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_Yk_N0uowPTDQ1Hwt:-NpecAVY3oStZ4VFtHWi:bb7f2mf) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/dxapp.json#L9)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

could this be changed to `vcf` or `vcf_file` or similar to be more descriptive please
</blockquote></details>

done
___
*[`dxapp.json` line 26 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_YXW46zCAvRSRciM2:-NpecUCR0FuJNMlfChEB:brpmqb3) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/dxapp.json#L26)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

since this isn't in 001_Reference project can the suggestion just be removed? This will be added in a workflow and probabbly not run interactively, so not really needed
</blockquote></details>

removed
___
*[`dxapp.json` line 34 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_YsXl9od9Ol1XhUUh:-NpecXKcBtu0OPrT4E4G:b9k5jjt) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/dxapp.json#L34)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

since this just outputs a single vcf, can this just be `vcf` or `output_vcf` etc
</blockquote></details>

changed 
___
*[`dxapp.json` line 45 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_Z3TW08dkY1gmANTo:-NpecdQf5k_KxF4W3k2P:by4fbct) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/dxapp.json#L45)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I assume this is very quick, could this just be 1 hour?
</blockquote></details>

changed to 1
___
*[`dxapp.json` line 59 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_ZBWf2LDR_r1oKkT4:-Npechbc8zFB577wYdV7:b7lfr1j) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/dxapp.json#L59)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I don't think this is needed is it? do you have the Python whl files needed in `/resources/home/dnanexus/packages`?
</blockquote></details>

removed (all in wheel)
___
*[`dxapp.json` line 72 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_ZKTJ2uuBzlnaGnGa:-Npeck6l8VmHyDWFowKk:brpmqb3) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/dxapp.json#L72)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

don't think is needed too, probably better to not have it to make sure we're not unintentionally relying on something remote
</blockquote></details>

removed
___
*[`README.md` line 1 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-NpdJ0VPErQHj0vbiI0W:-NpeclcJD5Zt2t1joKPe:bvnrpcm) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/README.md#L1)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

could you also make this fit the template example to match our other app readme structure, should be this:

```
<!-- dx-header -->
# AmazingApp (DNAnexus Platform App)
This could be used as a starting point when developing new apps for DNAnexus

<!-- Insert a description of your app here -->
## What does this app do?
Provide a brief description of this tool.

## What are the typical use cases for this app?
Describe use cases of the app.

## What are the inputs?
- list the required input files, specifying any formatting requirements

## What are the outputs?
- list the expected output files, specifying the format

## How to run this app from command line?
\```
add an example command of running this app from the CLI \
especially the (optional) inputs \
and recommended istance_type
\```

### This app was made by EMEE GLH
```


this is a useful page too for markdown syntax supported by GitHub: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
</blockquote></details>

updated
___
*[`README.md` line 9 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_ZVAb4Amrk5QWAYg9:-NpecnH2ABjPxLvg0_0-:b-rgcy6t) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/README.md#L9)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

make sure these inputs match whats in the dxapp.json :slightly_smiling_face:
</blockquote></details>

should be correct now

**Review by cnascim1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1)* status: 8 of 13 files reviewed, 16 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/vcf.py` line 75 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_ZzIyA1_uAt64pChz:-NpedTVEAF3zy2EoH6Cm:bsv417h) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/resources/home/dnanexus/vcf.py#L75)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

fyi if you're not familiar with this in bcftools its splitting the vep annotation which is all stored in a single INFO field string as `CSQ=...` into individual fields (i.e. the AFs and ClinVar annotation), this adds ` prefix of `CSQ_` with the `-p` option to each of the fields to stop any duplicates of other INFO fields and to know it is from the VEP annotation string. It then removes the original VEP CSQ INFO string with `bcftools annoatate -x` since it's no longer needed
</blockquote></details>

thank you!
___
*[`resources/home/dnanexus/vcf.py` line 151 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_a1FQ7iKmc_tnHjh9:-NpedWxF33mENITiyE-V:b-n9tkhd) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/resources/home/dnanexus/vcf.py#L151)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

input param doesn't match actual input
</blockquote></details>

changed
___
*[`resources/home/dnanexus/vcf.py` line 163 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_adByDrOSd0mdnNWi:-NpedYDF3LWdFD4Wqmew:b-b5c367) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/resources/home/dnanexus/vcf.py#L163)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

CSQ_Feature is transcript technically, minor thing but you will be creating a dict here of `{'transcript': [variant_1, variant_2]...}` and not gene, so could have multiple entries in the dict for one gene where it has more than one transcript annotation. Functionally it probably makes no difference, just for making it easier to understand what its doing :slightly_smiling_face:
</blockquote></details>

changed 
___
*[`resources/home/dnanexus/vcf.py` line 316 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_bwje-os0yF8fJlG6:-NpedaFVEbUgq3-855B8:bfu5ahg) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/resources/home/dnanexus/vcf.py#L316)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

it can be nice to add into the header a `Raises` section for any Exceptions you purposely might raise (or be raised from asserts), can make it easier to debug too having the context explained for future us, example here: https://github.com/eastgenomics/eggd_dias_batch/blob/18afe48d873e374e284e9e65b818cdc87945c6fe/resources/home/dnanexus/dias_batch/utils/utils.py#L426
</blockquote></details>

added :)
___
*[`src/code.sh` line 5 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_cKaa2F3zKl_RldUb:-NpedcIREbFQ_JNqzp1p:b-hfpv0l) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/src/code.sh#L5)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

these are just lines from the dx-app-wizard and can be deleted
</blockquote></details>

removed
___
*[`src/code.sh` line 21 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_cTRiBNzLNBVFSPsY:-NpeddQVE0fem1CUBBcM:b-hfpv0l) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/src/code.sh#L21)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this leading slash can be removed if your script is in `/resources/home/dnanexus/` as when the app starts it will be in the current working directory
</blockquote></details>

removed
___
*[`src/code.sh` line 23 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_cQSo9UnuHbMSnjZK:-NpedeNZAgY4pomzpeqV:bqezwsz) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/src/code.sh#L23)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

make sure these match the dxapp.json and the readme example
</blockquote></details>

should match now
___
*[`src/code.sh` line 26 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_cgAM-fBdPVdBw3ND:-Npedfkb64kFEDmHwZbI:b-hfpv0l) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/src/code.sh#L26)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this line can be deleted as this isn't an input here
</blockquote></details>

removed
___
*[`src/code.sh` line 28 at r1](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Np_cm7b6-uQhmbh-g5G:-Npedgnz4IWhNxGIcxhP:b-b5c367) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/a8c2d51dbc8e24473650655955e2e3fcf2371909/src/code.sh#L28)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

make sure this `out/dir_name` matches the output field in your dxapp.json output spec
</blockquote></details>

changed

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @cnascim1)

___
*[`README.md` line 1 at r2](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Npee4LA4mt7epcKnfxF:-Npee4LB2G8zzp0F2foJ:bb7phvt) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/1ff130f445230ed6233f9f018fcf007d0670e4af/README.md#L1)):*
> ```Markdown
> # eggd_ad_MANE_annotation
> ```

typo



_Code quote:_
```Markdown
ad
```
___
*[`README.md` line 11 at r2](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Npee7PVA5mcGzc5g8mm:-Npee7PVA5mcGzc5g8mn:bbf7ffx) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/1ff130f445230ed6233f9f018fcf007d0670e4af/README.md#L11)):*
> ```Markdown
>     -i input_vcf_annotated \
>     -t transcript_file \
>    
> ```

I think you want a closing triple back tick here to close the code block, as all the below ends up included

**Review by cnascim1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`README.md` line 1 at r2](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Npee4LA4mt7epcKnfxF:-NpefKB71--YsEDWi4NB:btptcv4) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/1ff130f445230ed6233f9f018fcf007d0670e4af/README.md#L1)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

typo
</blockquote></details>

fixed :)
___
*[`README.md` line 11 at r2](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1#-Npee7PVA5mcGzc5g8mm:-NpefNsv3BMObbMzlAgB:b-266mvq) ([raw file](https://github.com/eastgenomics/eggd_add_mane_annotation/blob/1ff130f445230ed6233f9f018fcf007d0670e4af/README.md#L11)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I think you want a closing triple back tick here to close the code block, as all the below ends up included

</blockquote></details>

fixed :)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_add_mane_annotation/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cnascim1)

**Pull request merged**
