### PR TITLE
fix input and output directories + vcf header version MANE

### PR DESCRIPTION
**Pull request by cnascim1**
The MANE version will appear as a PATH for the MANE transcripts file and its name. MANE transcripts file was created from the  MANE version published in https://ftp.ncbi.nlm.nih.gov/refseq/MANE/MANE_human/release_1.3/ but it is simplified.

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_add_MANE_annotation/2)

### CODE REVIEW

**Review by woook — COMMENTED** [review]
The path to transcript file has lost at letter at the end?
`##MANE\_transcripts=/home/dnanexus/in/transcript\_file/mane\_b38\_v1-3\_tx`

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_add_MANE_annotation/2#-:-NpuU8XQ86lWNaYXxUHl:b-rdvc6f)* status: 0 of 3 files reviewed, all discussions resolved

**Review by cnascim1 — COMMENTED** [review]
It lost the extension (.tsv), did another PR with the change. Should be fixed now :)

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_add_MANE_annotation/2#-:-Npxat9uEdJ_FmB7ISv0:bgawgv6)* status: 0 of 3 files reviewed, all discussions resolved

**Review by woook — COMMENTED** [review]
Are you planning to address the PEP8 points?

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_add_MANE_annotation/2#-:-NpyHCT9Cw0Wg-0lANbx:b3t0nnm)* status: 0 of 3 files reviewed, all discussions resolved

**Review by cnascim1 — COMMENTED** [review]
done 

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_add_MANE_annotation/2#-:-NpyPFcO03ro4rVwG9nq:b-7rl0jr)* status: 0 of 3 files reviewed, all discussions resolved

**Review by woook — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_add_MANE_annotation/2)* status: 2 of 3 files reviewed, all discussions resolved

**Review by woook — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_add_MANE_annotation/2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cnascim1)

**Pull request merged**
